// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineStore.Storage.MS_SQL;

#nullable disable

namespace OnlineStore.Storage.MS_SQL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241117195424_Create cost")]
    partial class Createcost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineStore.Storage.MS_SQL.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("OnlineStore.Storage.MS_SQL.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedbackId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("OnlineStore.Storage.MS_SQL.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Characteristics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<long>("CountOfProduct")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab4c680e-2273-43e1-b24a-5f9f72fa3cf5"),
                            Characteristics = "Размеры (Ш×В×Г): 100 × 200 × 60 см\r\nМатериал корпуса: ЛДСП высокого качества, устойчивое к механическим повреждениям и влаге.\r\nМатериал фасада: МДФ, покрытый защитной пленкой, легко чистится и стойкий к загрязнениям.\r\nЦвет: Корпус – Белый, Фасады – Дуб Сонома.",
                            Cost = 6990.0,
                            CountOfProduct = 100L,
                            ImageUrl = "~/images/kitchen1.jpg",
                            Name = "Кухня Деми Белый / Дуб Сонома 1 м",
                            ProductTypeId = new Guid("74ab8d65-384a-447c-9fa7-a71a775fa754")
                        },
                        new
                        {
                            Id = new Guid("44c80351-2597-4024-bf5b-3fab5b78494f"),
                            Characteristics = "Размеры (Ш×В×Г): 100 × 200 × 60 см, оптимальный вариант для небольшой кухни.\r\nМатериал корпуса: Высококачественное ЛДСП, устойчивое к влаге, царапинам и длительной эксплуатации.\r\nМатериал фасадов: ЛДСП с защитной пленкой, которая защищает поверхность от пятен и упрощает уход.\r\nЦвет: Корпус выполнен в цвете Авиньон (приглушенный серый), фасады — в светлом Перлино\r\nФурнитура: Металлические ручки и надежные петли, обеспечивающие плавное открытие и долговечность гарнитура.",
                            Cost = 5990.0,
                            CountOfProduct = 100L,
                            ImageUrl = "~/images/kitchen2.jpg",
                            Name = "Кухонный гарнитур Деми 1 м Авиньон/Перлино",
                            ProductTypeId = new Guid("74ab8d65-384a-447c-9fa7-a71a775fa754")
                        },
                        new
                        {
                            Id = new Guid("211a574f-a017-4e43-8215-2108e80caa93"),
                            Characteristics = "Размеры (Ш×В×Г): 170 × 200 × 60 см — гарнитур подойдет как для небольшой, так и для средней кухни, обеспечивая достаточно места для хранения.\r\nМатериал корпуса: ЛДСП, устойчивая к влаге и высоким температурам, с защитной поверхностью от пятен и царапин.\r\nМатериал фасадов: ЛДСП с ламинированным покрытием — практичное и долговечное решение для кухни.\r\nЦвет: Белоснежные фасады в сочетании с текстурой древесины Дуб Планк создают стильный, но нейтральный дизайн, который легко интегрируется в разные интерьеры.\r\nФурнитура: Современные металлические ручки и качественная фурнитура, обеспечивающая плавное и бесшумное открытие дверей.",
                            Cost = 19990.0,
                            CountOfProduct = 100L,
                            ImageUrl = "~/images/kitchen3.jpg",
                            Name = "Кухня Элен Белый/Дуб Планк, 1.7 м",
                            ProductTypeId = new Guid("74ab8d65-384a-447c-9fa7-a71a775fa754")
                        },
                        new
                        {
                            Id = new Guid("270a2b0b-fcf5-4b8f-a73a-680dafb92a52"),
                            Characteristics = "Размеры (Ш×В×Г): 240 × 210 × 60 см — идеально подходит для просторных кухонь, обеспечивая большое рабочее пространство и достаточное количество мест для хранения.\r\nМатериал корпуса: ЛДСП, устойчивая к механическим повреждениям, влаге и высокой температуре.\r\nМатериал фасадов: МДФ с глянцевым покрытием — обеспечивает легкий уход и привлекательный внешний вид.\r\nЦвет: Деликатный кремовый оттенок с текстурой дерева, который привносит в интерьер уют и гармонию.\r\nФурнитура: Надежные металлические ручки и высококачественные петли для плавного и бесшумного открытия дверей.",
                            Cost = 27990.0,
                            CountOfProduct = 100L,
                            ImageUrl = "~/images/kitchen4.jpg",
                            Name = "Кухонный гарнитур Регина, 2.4 м",
                            ProductTypeId = new Guid("74ab8d65-384a-447c-9fa7-a71a775fa754")
                        },
                        new
                        {
                            Id = new Guid("a1fba131-35c1-491e-aa78-9ca4388419f1"),
                            Characteristics = "Размеры (Ш×В×Г): 1500 × 2200 × 600 мм\r\nМатериал корпуса: ЛДСП высокого качества, устойчивое к износу и влаге.\r\nМатериал фасада: МДФ с покрытием, легкий в уходе и стойкий к царапинам.\r\nЦвет: Корпус и фасады выполнены в современном дизайне, с благородными оттенками дерева.\r\nФурнитура: Долговечная и надежная, из нержавеющей стали, обеспечивает плавное скольжение дверей.",
                            Cost = 20990.0,
                            CountOfProduct = 100L,
                            ImageUrl = "~/images/closet1.jpg",
                            Name = "Шкаф-купе Медея СБ-2907, 1500",
                            ProductTypeId = new Guid("4f6171f5-7166-4d15-887a-327b4dc7bf3a")
                        },
                        new
                        {
                            Id = new Guid("3a09b59d-460c-419d-9ae9-026cea92856b"),
                            Characteristics = "Размеры (Ш×В×Г): 1200 × 2000 × 500 мм\r\nМатериал корпуса: ЛДСП с высококачественным покрытием, стойким к повреждениям и влаге.\r\nМатериал фасада: МДФ с защитным покрытием, легким в уходе и устойчивым к царапинам.\r\nЦвет: Универсальные оттенки, подходящие для большинства интерьеров.\r\nФурнитура: Прочная и удобная в использовании, обеспечивает бесшумное открытие дверей.",
                            Cost = 13490.0,
                            CountOfProduct = 100L,
                            ImageUrl = "~/images/closet2.jpg",
                            Name = "Шкаф-купе Терра СБ-2610",
                            ProductTypeId = new Guid("4f6171f5-7166-4d15-887a-327b4dc7bf3a")
                        },
                        new
                        {
                            Id = new Guid("bd42f087-542b-4f75-94c2-754c0ea85a09"),
                            Characteristics = "Размеры (Ш×В×Г): 1500 × 2100 × 600 мм\r\nМатериал корпуса: ЛДСП высокого качества с устойчивым к повреждениям и влаге покрытием.\r\nМатериал фасада: МДФ с защитной пленкой, что облегчает уход и сохраняет внешний вид на долгое время.\r\nЦвет: Современные оттенки, подходящие для различных интерьеров.\r\nФурнитура: Надежная и долговечная, обеспечивает плавное и бесшумное движение дверей.",
                            Cost = 18990.0,
                            CountOfProduct = 100L,
                            ImageUrl = "~/images/closet3.jpg",
                            Name = "Шкаф-купе Бася СБ-2746/1",
                            ProductTypeId = new Guid("4f6171f5-7166-4d15-887a-327b4dc7bf3a")
                        },
                        new
                        {
                            Id = new Guid("34a53b41-fb4b-43b7-aa89-99e4868de882"),
                            Characteristics = "Размеры (Ш×В×Г): 1600 × 2200 × 600 мм\r\nМатериал корпуса: ЛДСП высокого качества, устойчивый к влаге и механическим повреждениям.\r\nМатериал фасада: Ламинированная поверхность, защищённая от царапин и легко чистится.\r\nЦвет: Современный универсальный оттенок, который гармонично впишется в любой интерьер.\r\nФурнитура: Надежная и долговечная, обеспечивает плавное открывание и закрывание дверей и ящиков.",
                            Cost = 17490.0,
                            CountOfProduct = 100L,
                            ImageUrl = "~/images/closet4.jpg",
                            Name = "Шкаф 4-дверный с ящиками Леон СБ-3364",
                            ProductTypeId = new Guid("4f6171f5-7166-4d15-887a-327b4dc7bf3a")
                        },
                        new
                        {
                            Id = new Guid("aadbc6c5-2a10-4083-9a6b-ed5595506ee3"),
                            Characteristics = "Размеры (Ш×В×Г): 2200 × 950 × 950 мм\r\nМатериал обивки: Экокожа высокого качества, устойчивая к загрязнениям и легко очищаемая.\r\nНаполнитель: Поролон с высокой плотностью для максимального комфорта.\r\nЦвет: Светлый бежевый, который легко комбинируется с любыми оттенками интерьера.\r\nМеханизм трансформации: Положение «книжка» для удобства сна и отдыха.",
                            Cost = 21990.0,
                            CountOfProduct = 50L,
                            ImageUrl = "~/images/sofa1.jpg",
                            Name = "Диван угловой Венеция",
                            ProductTypeId = new Guid("97913379-16e7-4f9a-82dd-d06b6b427ef3")
                        },
                        new
                        {
                            Id = new Guid("1c601af9-610c-4c6a-9731-3ac3ec460bba"),
                            Characteristics = "Размеры (Ш×В×Г): 1800 × 850 × 900 мм\r\nМатериал обивки: Ткань рогожка, приятная на ощупь и устойчивая к износу.\r\nНаполнитель: Холлофайбер, который долго сохраняет свою форму.\r\nЦвет: Темно-серый, универсальный и стильный оттенок для любой комнаты.\r\nФурнитура: Прочные металлические ножки и застежки, которые обеспечивают долговечность и стабильность.",
                            Cost = 12490.0,
                            CountOfProduct = 80L,
                            ImageUrl = "~/images/sofa2.jpg",
                            Name = "Диван прямой Классик",
                            ProductTypeId = new Guid("97913379-16e7-4f9a-82dd-d06b6b427ef3")
                        },
                        new
                        {
                            Id = new Guid("cbee4565-df46-410f-a302-3a35f188e599"),
                            Characteristics = "Размеры (Ш×В×Г): 2500 × 950 × 1000 мм\r\nМатериал обивки: Высококачественная микрофибра, не выгорает на солнце и легко чистится.\r\nНаполнитель: Мемори-фоам, адаптирующийся под форму тела, обеспечивающий комфорт при длительном сидении.\r\nЦвет: Синий с легким оттенком серого, придающий элегантности и свежести любому помещению.\r\nОсобенности: Раздвижной механизм, который позволяет преобразовывать диван в удобное спальное место.",
                            Cost = 29990.0,
                            CountOfProduct = 30L,
                            ImageUrl = "~/images/sofa3.jpg",
                            Name = "Диван модульный Лондон",
                            ProductTypeId = new Guid("97913379-16e7-4f9a-82dd-d06b6b427ef3")
                        },
                        new
                        {
                            Id = new Guid("a1decbd8-4894-44f0-8b2e-befc5af9599e"),
                            Characteristics = "Размеры (Ш×В×Г): 2400 × 1000 × 950 мм\r\nМатериал обивки: Бархат с эффектом перелива, который добавляет текстуры и уюта.\r\nНаполнитель: Водорослевый латекс, обеспечивающий комфорт и поддержку в течение всего дня.\r\nЦвет: Глубокий бордовый оттенок, который идеально подходит для современного интерьера.\r\nМеханизм трансформации: Аккордеон, что позволяет быстро разложить диван в удобное спальное место.",
                            Cost = 24990.0,
                            CountOfProduct = 60L,
                            ImageUrl = "~/images/sofa4.jpg",
                            Name = "Диван угловой Санторини",
                            ProductTypeId = new Guid("97913379-16e7-4f9a-82dd-d06b6b427ef3")
                        },
                        new
                        {
                            Id = new Guid("5278587b-c918-448e-809d-af2773c5a41f"),
                            Characteristics = "Размеры (Ш×Д×В): 1600 × 2000 × 900 мм\r\nМатериал каркаса: Ламинированный МДФ, устойчивый к механическим повреждениям и воздействию влаги.\r\nМатериал изголовья: Мягкое велюровое покрытие с современным дизайном.\r\nЦвет: Белый с серыми вставками, подходящий для различных интерьеров.\r\nОсобенности: Встроенные ящики для хранения постельных принадлежностей, легкость в сборке.",
                            Cost = 19990.0,
                            CountOfProduct = 40L,
                            ImageUrl = "~/images/catalog_bed1.jpg",
                            Name = "Кровать двухспальная Элита",
                            ProductTypeId = new Guid("1dd28342-5e5d-46e8-8965-33de065ac2ca")
                        },
                        new
                        {
                            Id = new Guid("90280c9c-37e5-424d-a957-8527eac4dbaa"),
                            Characteristics = "Размеры (Ш×Д×В): 1800 × 2000 × 950 мм\r\nМатериал каркаса: Бук и фанера, прочные и экологичные материалы.\r\nМатериал обивки: Ткань с эффектом кожи, приятная на ощупь и устойчивая к загрязнениям.\r\nЦвет: Классический черный с элементами дерева.\r\nОсобенности: Подъемный механизм для легкого доступа к месту хранения, максимальный комфорт для сна.",
                            Cost = 22490.0,
                            CountOfProduct = 25L,
                            ImageUrl = "~/images/catalog_bed2.jpg",
                            Name = "Кровать с подъемным механизмом Вальс",
                            ProductTypeId = new Guid("1dd28342-5e5d-46e8-8965-33de065ac2ca")
                        },
                        new
                        {
                            Id = new Guid("391b203d-23e0-4c23-ada5-be0b0f7a55d6"),
                            Characteristics = "Размеры (Ш×Д×В): 1400 × 2000 × 850 мм\r\nМатериал каркаса: Сталь с порошковым покрытием, защищающим от коррозии.\r\nМатериал обивки: Легкая дышащая ткань с антисептическими свойствами.\r\nЦвет: Серый металлик, современный и стильный.\r\nОсобенности: Компактный и удобный вариант для небольших помещений, простота в уходе.",
                            Cost = 15990.0,
                            CountOfProduct = 60L,
                            ImageUrl = "~/images/catalog_bed3.jpg",
                            Name = "Кровать с каркасом из металла Орион",
                            ProductTypeId = new Guid("1dd28342-5e5d-46e8-8965-33de065ac2ca")
                        },
                        new
                        {
                            Id = new Guid("ccd87ebe-2ff1-4eb5-a282-b69b2b830672"),
                            Characteristics = "Размеры (Ш×Д×В): 2000 × 2100 × 1000 мм\r\nМатериал каркаса: Массив дерева с дополнительной усиленной конструкцией.\r\nМатериал изголовья: Мягкое велюровое покрытие с декоративной отделкой.\r\nЦвет: Шоколадный с золотыми вставками, элегантный и роскошный.\r\nОсобенности: Удобное изголовье для чтения или отдыха, богатая отделка и внимание к деталям.",
                            Cost = 27990.0,
                            CountOfProduct = 35L,
                            ImageUrl = "~/images/catalog_bed4.jpg",
                            Name = "Кровать с мягким изголовьем Венеция",
                            ProductTypeId = new Guid("1dd28342-5e5d-46e8-8965-33de065ac2ca")
                        });
                });

            modelBuilder.Entity("OnlineStore.Storage.MS_SQL.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74ab8d65-384a-447c-9fa7-a71a775fa754"),
                            Name = "Кухни"
                        },
                        new
                        {
                            Id = new Guid("1dd28342-5e5d-46e8-8965-33de065ac2ca"),
                            Name = "Кровати"
                        },
                        new
                        {
                            Id = new Guid("4f6171f5-7166-4d15-887a-327b4dc7bf3a"),
                            Name = "Шкафы"
                        },
                        new
                        {
                            Id = new Guid("97913379-16e7-4f9a-82dd-d06b6b427ef3"),
                            Name = "Диваны"
                        });
                });

            modelBuilder.Entity("OnlineStore.Storage.MS_SQL.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalSum")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("ProductSale", b =>
                {
                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SalesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductsId", "SalesId");

                    b.HasIndex("SalesId");

                    b.ToTable("ProductsToSales", (string)null);
                });

            modelBuilder.Entity("OnlineStore.Storage.MS_SQL.Product", b =>
                {
                    b.HasOne("OnlineStore.Storage.MS_SQL.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("OnlineStore.Storage.MS_SQL.Sale", b =>
                {
                    b.HasOne("OnlineStore.Storage.MS_SQL.Client", "Client")
                        .WithMany("Sales")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ProductSale", b =>
                {
                    b.HasOne("OnlineStore.Storage.MS_SQL.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineStore.Storage.MS_SQL.Sale", null)
                        .WithMany()
                        .HasForeignKey("SalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineStore.Storage.MS_SQL.Client", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("OnlineStore.Storage.MS_SQL.ProductType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
